name: hermes_router
description: A declarative router for Flutter based on Navigation 2 supporting
  deep linking
version: 0.0.1
repository: https://github.com/dunatron/hermes_router

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  logging: ^1.0.0
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
